<a href="https://colab.research.google.com/github/Sharmaluvkesh/Movie-Genre-Classification---Deep-Learning-Approach/blob/main/movie_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Movie Genre Classification - Deep Learning Approach
This notebook contains a complete Deep Learning workflow using TensorFlow/Keras to perform multiclass classification on the provided movie dataset.

### **Import the dependencies**

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

### **Load the dataset**

In [4]:
df = pd.read_csv('movie_genre_classification_final.csv')
print('--- First 5 Rows ---')
print(df.head())
print('\n--- Data Shape ---')
print(df.shape)
print('\n--- Data Info ---')
df.info()

--- First 5 Rows ---
             Title  Year  Director  Duration  Rating   Votes  \
0  Winds of Fate 4  1980    R. Lee       167     4.1  182425   
1     Firestorm 11  2014   S. Chen       166     4.1  449351   
2    Silent Echo 2  2016   A. Khan       170     4.1  363328   
3    City Lights 4  1982  L. Zhang       170     9.9   62371   
4   Broken Truth 1  1990  L. Zhang        91     5.3    4600   

                                         Description  Language Country  \
0   A touching love story with heartwarming moments.   Spanish   China   
1  A fast-paced thriller with intense action scenes.    Korean   China   
2  A fast-paced thriller with intense action scenes.    Korean   Japan   
3  An emotional journey exploring complex charact...  Japanese   Japan   
4  An imaginative world filled with magic and won...    Korean     USA   

   Budget_USD  BoxOffice_USD    Genre Production_Company Content_Rating  \
0    39979615      179936008  Romance         DreamWorks              R   

* Data is **Balanced** across genres.

In [5]:
print(df['Genre'].value_counts())
df = df.drop(columns=['Title'])
df.info()

Genre
Horror      7260
Drama       7187
Romance     7169
Thriller    7118
Action      7107
Fantasy     7100
Comedy      7059
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Year                50000 non-null  int64  
 1   Director            50000 non-null  object 
 2   Duration            50000 non-null  int64  
 3   Rating              50000 non-null  float64
 4   Votes               50000 non-null  int64  
 5   Description         50000 non-null  object 
 6   Language            50000 non-null  object 
 7   Country             50000 non-null  object 
 8   Budget_USD          50000 non-null  int64  
 9   BoxOffice_USD       50000 non-null  int64  
 10  Genre               50000 non-null  object 
 11  Production_Company  50000 non-null  object 
 12  Content_Rating      50000 non-null  object 
 13  

### **Preprocess and Encode Features**

In [6]:
le = LabelEncoder()
df['Genre'] = le.fit_transform(df['Genre'])
df = pd.get_dummies(df, columns=['Description', 'Language', 'Country', 'Production_Company', 'Content_Rating', 'Lead_Actor', 'Director'], drop_first=True)
df.head()

,Year,Duration,Rating,Votes,Budget_USD,BoxOffice_USD,Genre,Num_Awards,Critic_Reviews,Description_A light-hearted comedy that guarantees laughter.,...,Lead_Actor_Tom Hanks,Director_D. Patel,Director_J. Smith,Director_L. Zhang,Director_M. Brown,Director_N. Roy,Director_P. Adams,Director_R. Lee,Director_S. Chen,Director_T. Johnson
0,1980,167,4.1,182425,39979615,179936008,5,8,229,False,...,False,False,False,False,False,False,False,True,False,False
1,2014,166,4.1,449351,116404774,802121619,0,20,466,False,...,False,False,False,False,False,False,False,False,True,False
2,2016,170,4.1,363328,166261330,225526871,0,16,539,False,...,False,False,False,False,False,False,False,False,False,False
3,1982,170,9.9,62371,28861315,69813738,2,15,606,False,...,False,False,False,True,False,False,False,False,False,False
4,1990,91,5.3,4600,43890403,375136716,3,6,330,False,...,False,False,False,True,False,False,False,False,False,False


### **Split Features and Targets**

In [7]:
x = df.drop(columns='Genre', axis=1)
y = df['Genre']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)
print("Training dimensions:", x_train.shape)

Training dimensions: (40000, 57)


### **Feature Scaling**

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

### **Building the Neural Network**

In [9]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(57,)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(7, activation='softmax')
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 57)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         1,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 7)              │           231 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,087 (8.15 KB)

 Trainable params: 2,087 (8.15 KB)

 Non-trainable params: 0 (0.00 B)

### **Compile and Train the Network**

In [10]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=7, batch_size=32, validation_split=0.1)

Epoch 1/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9058 - loss: 0.3706 - val_accuracy: 1.0000 - val_loss: 0.0129
Epoch 2/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 1.0000 - loss: 0.0053 - val_accuracy: 1.0000 - val_loss: 0.0022
Epoch 3/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 7.4454e-04
Epoch 4/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 4.7789e-04 - val_accuracy: 1.0000 - val_loss: 3.1786e-04
Epoch 5/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 2.1480e-04 - val_accuracy: 1.0000 - val_loss: 1.5060e-04
Epoch 6/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 1.0446e-04 - val_accuracy: 1.0000 - val_loss: 7.5359e-05
Epoch 7/7
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 1.0000 - loss: 5.3035e-05 - val_accuracy: 1.0000 - val_loss: 3.8889e-05


### **Generate Training Predictions**

In [11]:
train_pred = model.predict(x_train)
train_pred = [np.argmax(i) for i in train_pred]
train_pred

1250/1250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step


[np.int64(6),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(5),
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(1),
 np.int64(6),
 np.int64(2),
 np.int64(1),
 np.int64(3),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(1),
 np.int64(3),
 np.int64(6),
 np.int64(6),
 np.int64(1),
 np.int64(2),
 np.int64(6),
 np.int64(4),
 np.int64(6),
 np.int64(4),
 np.int64(4),
 np.int64(5),
 np.int64(2),
 np.int64(0),
 np.int64(3),
 np.int64(3),
 np.int64(6),
 np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(4),
 np.int64(0),
 np.int64(3),
 np.int64(5),
 np.int64(6),
 np.int64(0),
 np.int64(0),
 np.int64(6),
 np.int64(2),
 np.int64(6),
 np.int64(5),
 np.int64(1),
 np.int64(1),
 np.int64(5),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(6),
 np.int64(5),
 np.int64(2),
 np.int64(6),
 np.int64(0),
 np.int64(0),
 np.int64(0),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(6),
 np.int64(0),
 np.int64(6),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.in

### **Generate Testing Predictions**

In [12]:
test_pred = model.predict(x_test)
test_pred = [np.argmax(i) for i in test_pred]
test_pred

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


[np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(4),
 np.int64(3),
 np.int64(5),
 np.int64(3),
 np.int64(2),
 np.int64(5),
 np.int64(6),
 np.int64(2),
 np.int64(6),
 np.int64(0),
 np.int64(4),
 np.int64(4),
 np.int64(6),
 np.int64(6),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(3),
 np.int64(1),
 np.int64(5),
 np.int64(3),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(3),
 np.int64(1),
 np.int64(4),
 np.int64(6),
 np.int64(3),
 np.int64(4),
 np.int64(0),
 np.int64(2),
 np.int64(1),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(0),
 np.int64(5),
 np.int64(3),
 np.int64(2),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(2),
 np.int64(0),
 np.int64(4),
 np.int64(6),
 np.int64(0),
 np.int64(2),
 np.int64(3),
 np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(5),
 np.int64(5),
 np.int64(4),
 np.int64(3),
 np.int64(1),
 np.int64(5),
 np.int64(0),
 np.in

### **Model Evaluation**

In [13]:
print('Train Acc :-', accuracy_score(y_train, train_pred))
print('Test Acc :-', accuracy_score(y_test, test_pred))

print('\nTrain Confusion Matrix :-\n', confusion_matrix(y_train, train_pred))
print('Test Confusion Matrix :-\n', confusion_matrix(y_test, test_pred))

print('\nTrain Precision :-', precision_score(y_train, train_pred, average='macro'))
print('Test Precision :-', precision_score(y_test, test_pred, average='macro'))

print('\nTrain Recall :-', recall_score(y_train, train_pred, average='macro'))
print('Test Recall :-', recall_score(y_test, test_pred, average='macro'))

Train Acc :- 1.0
Test Acc :- 1.0

Train Confusion Matrix :-
 [[5683    0    0    0    0    0    0]
 [   0 5626    0    0    0    0    0]
 [   0    0 5756    0    0    0    0]
 [   0    0    0 5714    0    0    0]
 [   0    0    0    0 5804    0    0]
 [   0    0    0    0    0 5694    0]
 [   0    0    0    0    0    0 5723]]
Test Confusion Matrix :-
 [[1424    0    0    0    0    0    0]
 [   0 1433    0    0    0    0    0]
 [   0    0 1431    0    0    0    0]
 [   0    0    0 1386    0    0    0]
 [   0    0    0    0 1456    0    0]
 [   0    0    0    0    0 1475    0]
 [   0    0    0    0    0    0 1395]]

Train Precision :- 1.0
Test Precision :- 1.0

Train Recall :- 1.0
Test Recall :- 1.0
